import { defineConfig } from '@pandacss/dev';

import { designSystemPandaConfig } from './panda.shared';

// See PANDA_NOTES.md for the Panda gotchas that bite consumers of this preset:
//
// - `staticCss` is a ROOT-config key (it lives on `designSystemPandaConfig`
//   / this object, NOT in the exported preset — Panda ignores `staticCss`
//   declared inside a preset). Any recipe with a variant toggled by RUNTIME
//   state (e.g. `interactiveItem({ selected })`) emits NO CSS unless its
//   variants are pre-generated via `staticCss.recipes`. Consumers must add
//   their own `staticCss` block here; installing the preset alone is not enough.
// - CSS is generated by consumers, not this library (build is `tsc`; there
//   is no `cssgen` here). Consumers that want new utilities to hot-reload
//   without a manual regen should adopt the `@pandacss/dev/postcss` plugin.
export default defineConfig({
  ...designSystemPandaConfig,
  include: ['./src/**/*.{js,jsx,ts,tsx}'],
  outdir: 'styled-system',
});
